language: go,node_js
node_js:
  - "node"
dist: trusty
sudo: false
cache: yarn
go:
  - "1.13.x"
install: false
git:
  depth: 1
install:
 - make deps
branches:
  only:
    - master
notifications:
  email: false
before_install:
  - go version
script:
 - make build-all