language: go,node_js
dist: xenial
sudo: false
cache: yarn
install: false
git:
  depth: 1
install:
 - make deps
branches:
  only:
    - master
notifications:
  email: false
matrix:
  include:
    - language: go
      go: 1.13.5
      before_install:
        - make deps
      script:
        - make build-linux
        - make build-mac
        - make build-windows
    - language: node_js
      node_js: 10.18.0
      before_install:
        - make deps
      script:
        - make build-web