language: go,node_js
node_js:
  - "10.18.0"
go:
  - 1.13.5
dist: xenial
sudo: false
cache: yarn
install: false
git:
  depth: 1
install:
 - make deps
branches:
  only:
    - master
notifications:
  email: false
before_install:
  - go version
script:
 - make build-all